### ISSUE TITLE
NullPointerException instantiating SecretsManagerConfigProvider

### ISSUE THREAD

**Issue by vtstanescu** [aws-samples/msk-config-providers#26]
Hello,

We are encountering NPEs when using the Config provider for Secrets Manager, we haven't tried any other.
These seem to occur randomly, but frequently, when a worker or connector is started for the first time.
We eventually had to hardcode values in the connector config to get us going in a connector running across multiple workers.

Kafka version is 3.6.0
Java distribution and version is Amazon Corretto 22
MSK config providers version is 0.2.0

A connector `/stop` & `/resume` seemed to resolve the issue in the past when we were using only 1 worker, but with multiple workers, the issues pops up randomly on 1 or more workers.

```
[2024-08-26 06:58:35,156] ERROR [Worker clientId=connect-1, groupId=connect-<redacted>] Couldn't instantiate task <redacted>-5 because it has an invalid task configuration. This task will not execute until reconfigured. (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1921)
java.lang.NullPointerException: Cannot invoke "software.amazon.awssdk.utils.AttributeMap$Value.get(software.amazon.awssdk.utils.AttributeMap$LazyValueSource)" because "value" is null
	at software.amazon.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:396)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at software.amazon.awssdk.utils.AttributeMap$Builder.build(AttributeMap.java:362)
	at software.amazon.awssdk.core.client.config.SdkClientConfiguration$Builder.build(SdkClientConfiguration.java:232)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:178)
	at software.amazon.awssdk.services.secretsmanager.DefaultSecretsManagerClientBuilder.buildClient(DefaultSecretsManagerClientBuilder.java:29)
	at software.amazon.awssdk.services.secretsmanager.DefaultSecretsManagerClientBuilder.buildClient(DefaultSecretsManagerClientBuilder.java:22)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:155)
	at com.amazonaws.kafka.config.providers.SecretsManagerConfigProvider.checkOrInitSecretManagerClient(SecretsManagerConfigProvider.java:173)
	at com.amazonaws.kafka.config.providers.SecretsManagerConfigProvider.get(SecretsManagerConfigProvider.java:134)
	at org.apache.kafka.common.config.ConfigTransformer.transform(ConfigTransformer.java:103)
	at org.apache.kafka.connect.runtime.WorkerConfigTransformer.transform(WorkerConfigTransformer.java:58)
	at org.apache.kafka.connect.storage.ClusterConfigState.connectorConfig(ClusterConfigState.java:152)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1866)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$getTaskStartingCallable$35(DistributedHerder.java:1919)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by bdesert** [comment]
checking on this

**Comment by vtstanescu** [comment]
Hi, @bdesert!
Any updates on this?

I'm wondering if this can be caused by missing network connectivity between the workers of the Kafka Connect cluster.

We are using the distributed connect, so one worker is the leader of the connector. I'm not sure about the implementation details in Kafka Connect, but I assume the leader worker of the connector generates the "rendered" config by reading data from the config providers and then passes the "rendered" config to all workers that are running tasks for the connector.  
If the workers cannot communicate among themselves, eg. EC2 security group rules are missing, it may cause this issue.

We are using a self-hosted Kafka Connect cluster in AWS, and will test the usage of `secretsmanager` config provider again, to see if the issue reoccurs after we've added the needed SGR to allow traffic between the Kafka Connect workers. I don't have high expectations, though, as we've seen the same NPEs when running our connector in Amazon MSK Connect service, but let's see.

**Comment by bdesert** [comment]
hi @vtstanescu ,
ok, got my head around it and I think I have solution for this. I think the issues is caused by some type of expiration happening because I keep the builder open without rebuilding it. I think, if we catch this exception and rebuild the builder, this should solve the issue. alternatively we can create the builder every time, but this will be expensive (performance wise), as kafka connect is re-evaluating configuration all the time, using cached client would be way faster.
so, I'll provide a fix in the next week or two and will tag you on PR to review

**Comment by vtstanescu** [comment]
hi @bdesert,
Any news? From you last comment it's clear the issue is not caused by what I explained [here](https://github.com/aws-samples/msk-config-providers/issues/26#issuecomment-2410749287). Happy to test if you have a draft.

**Comment by bdesert** [comment]
hi @vtstanescu ,
Can you please check the [PR](https://github.com/aws-samples/msk-config-providers/pull/30) i've submitted?
Let me know if you are able to build the JAR from [my brunch](https://github.com/aws-samples/msk-config-providers/tree/ISSUE-26-NPE) and test it.

**Comment by vtstanescu** [comment]
hi @bdesert,
I'll try it this week and get back to you. Just looking at the PR, instead of a timer, I'm wondering if it should instead catch the exception when building the client and recreate the builder in that case.  
How do we know 1 minute TTL is enough?

**Comment by vtstanescu** [comment]
Tried a build of your branch @bdesert and I get a whole different error now, but consistently and on all tasks, thus it blocks the connector from starting all together.  
Trace:
```
java.lang.NoSuchFieldError: Class software.amazon.awssdk.core.client.config.SdkClientOption does not have member field 'software.amazon.awssdk.core.client.config.SdkClientOption CLIENT_ENDPOINT_PROVIDER'  at software.amazon.awssdk.services.secretsmanager.DefaultSecretsManagerBaseClientBuilder.finalizeServiceConfiguration(DefaultSecretsManagerBaseClientBuilder.java:101)
  at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:167)
  at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:197)
  at software.amazon.awssdk.services.secretsmanager.DefaultSecretsManagerClientBuilder.buildClient(DefaultSecretsManagerClientBuilder.java:38)
  at software.amazon.awssdk.services.secretsmanager.DefaultSecretsManagerClientBuilder.buildClient(DefaultSecretsManagerClientBuilder.java:25)
  at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:164)
  at com.amazonaws.kafka.config.providers.SecretsManagerConfigProvider.checkOrInitSecretManagerClient(SecretsManagerConfigProvider.java:184)
  at com.amazonaws.kafka.config.providers.SecretsManagerConfigProvider.get(SecretsManagerConfigProvider.java:143)
  at org.apache.kafka.common.config.ConfigTransformer.transform(ConfigTransformer.java:103)
  at org.apache.kafka.connect.runtime.WorkerConfigTransformer.transform(WorkerConfigTransformer.java:58)
  at org.apache.kafka.connect.storage.ClusterConfigState.connectorConfig(ClusterConfigState.java:152)
  at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1866)
  at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$getTaskStartingCallable$35(DistributedHerder.java:1919)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.base/java.lang.Thread.run(Thread.java:1570)
```

I have a setup in place now to build the msk-config-providers project and package it in Kafka Connect to test it. Happy to sync on Slack or e-mail to speed this up if you're available.

**Comment by patrickherrera** [comment]
Hi all, we've been hitting this issue quite frequently, and I can confirm that the [PR](https://github.com/aws-samples/msk-config-providers/pull/30) fixes the issue.  I added this to a local copy of the library that is on a slightly older version so I am not encountering the `CLIENT_ENDPOINT_PROVIDER` issue (yet).

**Comment by bdesert** [comment]
#33 fixes this issue. I'll close this issue once I cut new release

**Comment by bdesert** [comment]
thanks for reporting and contributing!
https://github.com/aws-samples/msk-config-providers/pull/33 fixes the issue, it's been fixed now in [release 0.4.0](https://github.com/aws-samples/msk-config-providers/releases/tag/r0.4.0)
